---
title: "assignment1_judith"
author: "j. van der Wolf"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#library
library(tidyverse)
library(dplyr)

getwd()
#data
data <- read.csv("../Airbnb_Open_Data.csv")
```

#Datacleaning 
## Duplicates
```{r}
# Print total duplicates
sum(duplicated(data))

# Remove duplicate rows 
data <- data %>% unique()
```

## Subset & Rename
```{r}
# Subset data
data <- data %>%
  dplyr::select(cancellation_policy,
                room.type,
                Construction.year,
                service.fee,
                minimum.nights,
                number.of.reviews,
                reviews.per.month,
                review.rate.number,
                availability.365,
                price)

# Rename column names to snake_case format
data <- data %>%
  dplyr::rename(
    room_type = room.type,
    construction_year = Construction.year,
    service_fee = service.fee,
    minimum_nights = minimum.nights,
    number_of_reviews = number.of.reviews,
    reviews_per_month = reviews.per.month,
    review_rate_number = review.rate.number,
    availability_365 = availability.365,
    price_usd = price
  )
```

## Missing values
```{r}
# Count missing data
data %>%
  dplyr::summarise(across(everything(), ~ sum(is.na(.)))) %>%
  tidyr::pivot_longer(
    cols = everything(),
    names_to = "Variable",
    values_to = "NA Count"
  )
```

```{r}
# Drop all rows that contain empty or missing values
data <- data %>%
  # Convert empty character variables to NA
  mutate(across(where(is.character), ~ trimws(.))) %>%
  mutate(across(where(is.character), ~ na_if(., ""))) %>%
  
  # Drop records with NA values
  drop_na()
```

## Measurement level check and adjustment
```{r}
# Convert variables to factor types
data <- data %>%
  dplyr::mutate(
    cancellation_policy = factor(cancellation_policy, 
                                 levels = c("flexible", "moderate", "strict"),
                                 ordered = TRUE),
    room_type = factor(room_type,
                       ordered = FALSE)
  )

# View new structure
str(data$cancellation_policy)
str(data$room_type)
```

```{r}
# Parse price numeric values
data <- data %>%
  dplyr::mutate(
    price_usd = parse_number(price_usd),
    service_fee = parse_number(service_fee)
  )
```

#Individual variables 

##construction_year
```{r}
(summary_constr <- data %>%
  summarise(min(construction_year),
            max(construction_year),
            median(construction_year)))

#reken uit hoeveel observaties er zijn voor elk jaartal
data %>% 
  count(construction_year)

#percentages
table(data$construction_year)/ nrow(data)

#omdat er maar 20 jaartallen zijn; bar-chart laat visueel beter zien vind ik. 
ggplot(data, aes(construction_year)) +
  geom_bar()

```


##service_fee
```{r}
summary(data$service_fee)
ggplot(data, aes(service_fee)) +
  geom_histogram(binwidth = 0.3)
```

##minimum_nights
```{r}
summary(data$minimum_nights)
#Extreme low value (negative = not possibe) and extreme high value (5645 = ingevuld om andere reden dan om aan te geven wat minimale nachten zijn - bijv. voor een periode niet verhuren, maar wel omhoog blijven komen in zoeksuggesties e.d.)

#counting negative values (10)
data %>% 
  count(minimum_nights < 0)

#counting high values => bigger than 1 year, 365 = 17 (bigger than 1/2 year = 93)
data %>% 
  count(minimum_nights > 365)

data %>%
  filter(between(minimum_nights, 0, 365)) %>%
   summarise(min(minimum_nights),
            max(minimum_nights),
            mean(minimum_nights))

data %>%
  filter(between(minimum_nights, 0, 365)) %>%
  ggplot(aes(minimum_nights)) +
  geom_histogram(binwidth = 0.3)

```







##Subset
#```{r}
airbnb_raw <- airbnb_raw %>%
  select(cancellation_policy, 
         room.type, 
         Construction.year,
         service.fee,
         minimum.nights,
         number.of.reviews,
         reviews.per.month,
         review.rate.number,
         availability.365,
         price)
```

##Duplications (12012) 
#```{r}
sum(duplicated(airbnb_raw))

#Remove duplicate rows 
airbnb_raw1 <- airbnb_raw %>% unique()
```

##Measurementlevel  
#```{r}
str(airbnb_raw1)

#Converting service.fee and price from chr. to numb
airbnb_raw2 <- airbnb_raw1 %>%
  mutate(price = parse_number(price), service.fee = parse_number(service.fee))

#Converting cancellation_policy, room.type from chr. to factor 
airbnb_raw2 <- mutate(airbnb_raw2,
              cancel_pol = as_factor(cancellation_policy),
              roomtype = as_factor(room.type)
              )
str(airbnb_raw2)
```

##Missing values 
#```{r}
colSums(is.na(airbnb_raw2[, c("cancel_pol", "price", "roomtype", "Construction.year", "service.fee", "minimum.nights", "number.of.reviews", "reviews.per.month", "review.rate.number", "availability.365" )]))

#Q: do we want to remove all missing data observations? 
```

##Weird shit 
#```{r}
#Roomtype
#only private room, entire home , shared room in analysis (hotel room is about certain services regardless if room is private/shared.)
airbnb_raw2 <- airbnb_raw2 %>% 
  filter(roomtype != "Hotel room") %>%   
  droplevels()

#Cancel_pol
#only maintain levels "stric", "moderate" and "flexible", there is an unknown "" level that contains 76 observations.
levels(airbnb_raw2$cancel_pol)
table(airbnb_raw2$cancel_pol)

airbnb_raw2 <- airbnb_raw2 %>% 
  filter(cancel_pol != "") %>%   
  droplevels()

levels(airbnb_raw2$cancel_pol)

#Constructionyear -> suggestion to remove NA's (204).
summary(airbnb_raw2$Construction.year)

#Service.fee -> suggestion to remove NA's (273)
summary(airbnb_raw2$service.fee) 

#minimum.nights -> suggestion to remove NA's (391)
#looking at interquartiles noticable huge outliers. 
#Suggestion => only keep minimum.nights in a range between 0 and 2000. The negative numbers don't make sense to me. 
summary(airbnb_raw2$minimum.nights)
datanight <- airbnb_raw2 %>% 
  pivot_longer(cols = "minimum.nights", names_to = "minN", values_to = "Value")

(outliernight <- ggplot(datanight, aes(x = minN, y = Value)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 16, outlier.size = 2) +
  labs(title = "Boxplots of minimumnight", x = "min.night", y = "Value") +
  theme_minimal())

```

