---
title: "assignment1_poging2"
author: "j. van der Wolf"
date: "2024-12-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#library
library(tidyverse)
library(dplyr)
library(MLmetrics)

getwd()
#data
data <- read.csv("../Airbnb_Open_Data.csv")
```

# Datacleaning 
# Duplicates
```{r}
# Print totaal aantal duplicaten
sum(duplicated(data$host.id))

# Verwijder duplicate rijen 
data <- data %>% 
  dplyr::distinct(host.id, .keep_all = TRUE)
```

# Subset & Rename
```{r}
# Subset data
# Selecteer de relevante kolommen voor de analyse
data <- data %>%
  dplyr::select(cancellation_policy,
                room.type,
                Construction.year,
                service.fee,
                minimum.nights,
                number.of.reviews,
                reviews.per.month,
                review.rate.number,
                availability.365,
                price)

# Hernoem de kolommen naar snake_case format
data <- data %>%
  dplyr::rename(
    room_type = room.type,
    construction_year = Construction.year,
    service_fee = service.fee,
    minimum_nights = minimum.nights,
    number_of_reviews = number.of.reviews,
    reviews_per_month = reviews.per.month,
    review_rate_number = review.rate.number,
    availability_365 = availability.365,
    price_usd = price
  )
```

# Transformatie van variabelen 
```{r}
data <- data %>% 
  mutate(room_type = as.factor(room_type)) %>%
  mutate(review_rate_number = as.factor(review_rate_number)) %>%
  mutate(cancellation_policy = as.factor(cancellation_policy)) %>%
  mutate(price_usd = parse_number(price_usd)) %>%
  mutate(service_fee = parse_number(service_fee))
```

# Missende values
```{r}
summary(is.na(data))
```

# Additionele outliers en onmogelijke values
```{r}
#Check reviews_per_month voor onmogelijke values
data %>% 
  count(reviews_per_month)

#cancellation_policy => heeft een lege category with 76 n
data %>% 
  count(cancellation_policy)

#room_type
data %>% 
  count(room_type)

#number_of_reviews
data %>% 
  count(number_of_reviews)

#construction_year
data %>% 
  count(construction_year)

#review_rate_number
data %>% 
  count(review_rate_number)

#availability_365: De range is -10 tot 426, en er is een uitschieter: 3677.
data %>% 
  count(availability_365)

#service_fee
data %>% 
  count(service_fee)
#price_usd 
data %>% 
  count(price_usd)

#minimum_nights. Onmogelijke waardes gevonden van: -1223, -365, -200, -125, -12, -10(4), -5, -3, -2, -1, en een aantal zijn hoger dan 365.
data %>% 
  count(minimum_nights)

```

# Verwijder NA's en andere onmogelijke waarden
```{r}
data <- data %>%
  select(-service_fee) %>%
  filter(between(availability_365, 0, 365)) %>%
  filter(between(minimum_nights, 0, 365)) %>%
  mutate(across(where(is.character), ~ trimws(.))) %>%
  mutate(across(where(is.character), ~ na_if(., ""))) %>%
  drop_na()
```

# Controleer of er nog ontbrekende waarden zijn na het schoonmaakproces
```{r}
summary(is.na(data))
```

# Regressieanalyse
```{r}
#Regressieanalyse voor de relatie tussen review_rate_number en price_usd: Des te hoger de review rate number, des te lager de prijs.
model1 <- lm(price_usd ~ review_rate_number, data)
summary(model1)


model2<- lm(price_usd ~ room_type + review_rate_number, data)
model2
```
# Backward
```{r}
# Voer een backward selectie uit om het beste model te vinden
backward_model <- lm(price_usd ~ ., data)
backward_model <- step(backward_model, direction = "backward")

# Voer een forward selectie uit na de backward selectie
forward_model <- step(backward_model, direction = "forward", scope = formula(~ .))
```



